-- 1. Create Gallery Logs Table
CREATE TABLE IF NOT EXISTS public.gallery_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    crop TEXT NOT NULL,
    category TEXT NOT NULL,
    img TEXT NOT NULL, -- Base64 Data URL or storage bucket URL
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    author_name TEXT NOT NULL,
    author_avatar TEXT NOT NULL,
    description TEXT,
    telemetry JSONB NOT NULL DEFAULT '{"stage": "N/A", "moisture": "N/A", "ph": "N/A", "temp": "N/A"}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create Comments Table
CREATE TABLE IF NOT EXISTS public.gallery_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_id BIGINT REFERENCES public.gallery_logs(id) ON DELETE CASCADE NOT NULL,
    author TEXT NOT NULL DEFAULT 'Administrator',
    avatar TEXT NOT NULL,
    text TEXT NOT NULL,
    time TEXT NOT NULL DEFAULT 'Just now',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Create Settings Table (Single-row configuration)
CREATE TABLE IF NOT EXISTS public.system_settings (
    id INT PRIMARY KEY DEFAULT 1,
    profile_name TEXT NOT NULL DEFAULT 'Senior Director Baba Tunde',
    profile_email TEXT NOT NULL DEFAULT 'baba.tunde@resolvefarms.com',
    profile_phone TEXT DEFAULT '+234 803 123 4567',
    profile_role TEXT NOT NULL DEFAULT 'Senior Farm Director',
    profile_location TEXT DEFAULT 'Enugu Field Block A-C',
    profile_avatar TEXT NOT NULL DEFAULT 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=60',
    temp_unit TEXT NOT NULL DEFAULT '°C',
    area_unit TEXT NOT NULL DEFAULT 'Hectares',
    moisture_min INT NOT NULL DEFAULT 60,
    ph_min NUMERIC(3,1) NOT NULL DEFAULT 6.0,
    ph_max NUMERIC(3,1) NOT NULL DEFAULT 7.2,
    temp_warning_max INT NOT NULL DEFAULT 35,
    low_stock_alert BOOLEAN NOT NULL DEFAULT TRUE,
    order_success_alert BOOLEAN NOT NULL DEFAULT FALSE,
    weekly_report BOOLEAN NOT NULL DEFAULT TRUE,
    two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT check_single_row CHECK (id = 1)
);

-- Enable Row Level Security (RLS) or public access bypass for testing
ALTER TABLE public.gallery_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;

-- Set up RLS Policies (allows reads, inserts, and deletes for all users)
DROP POLICY IF EXISTS "Allow anonymous read access" ON public.gallery_logs;
CREATE POLICY "Allow anonymous read access" ON public.gallery_logs FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow anonymous write access" ON public.gallery_logs;
CREATE POLICY "Allow anonymous write access" ON public.gallery_logs FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anonymous delete access" ON public.gallery_logs;
CREATE POLICY "Allow anonymous delete access" ON public.gallery_logs FOR DELETE USING (true);

DROP POLICY IF EXISTS "Allow anonymous read access" ON public.gallery_comments;
CREATE POLICY "Allow anonymous read access" ON public.gallery_comments FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow anonymous write access" ON public.gallery_comments;
CREATE POLICY "Allow anonymous write access" ON public.gallery_comments FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anonymous read access" ON public.system_settings;
CREATE POLICY "Allow anonymous read access" ON public.system_settings FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow anonymous update access" ON public.system_settings;
CREATE POLICY "Allow anonymous update access" ON public.system_settings FOR UPDATE USING (true);

-- Insert Default Settings Single Row
INSERT INTO public.system_settings (id) VALUES (1) ON CONFLICT DO NOTHING;

-- 4. Create Products Table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    price INT NOT NULL,
    unit TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'published',
    img TEXT NOT NULL, -- Base64 Data URL or storage bucket URL
    qty INT NOT NULL DEFAULT 0,
    min INT NOT NULL DEFAULT 50,
    max INT NOT NULL DEFAULT 500,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Set up RLS Policies for Products
DROP POLICY IF EXISTS "Allow anonymous read access" ON public.products;
CREATE POLICY "Allow anonymous read access" ON public.products FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow anonymous write access" ON public.products;
CREATE POLICY "Allow anonymous write access" ON public.products FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anonymous update access" ON public.products;
CREATE POLICY "Allow anonymous update access" ON public.products FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow anonymous delete access" ON public.products;
CREATE POLICY "Allow anonymous delete access" ON public.products FOR DELETE USING (true);
-- 5. Seed Initial Products Data
INSERT INTO public.products (id, name, category, price, unit, status, img) VALUES
(1, 'Habanero Pepper', 'Peppers', 1800, 'kg', 'published', '/src/assets/habanero_pepper.png'),
(2, 'African Corn', 'Corn', 2200, 'bag', 'published', '/src/assets/african_corn.png'),
(3, 'Roma Tomatoes', 'Tomatoes', 1500, 'kg', 'published', '/src/assets/roma_tomatoes.png'),
(4, 'Yellow Bell Pepper', 'Peppers', 2000, 'kg', 'draft', '/src/assets/yellow_bell_pepper.png'),
(5, 'Cassava Tubers', 'Tubers', 900, 'bag', 'published', '/src/assets/cassava_tubers.png'),
(6, 'Sweet Potatoes', 'Tubers', 1100, 'kg', 'draft', '/src/assets/sweet_potatoes.png')
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    price = EXCLUDED.price,
    unit = EXCLUDED.unit,
    status = EXCLUDED.status,
    img = EXCLUDED.img;

-- 6. Seed Initial Gallery Logs Data
INSERT INTO public.gallery_logs (id, title, crop, category, img, date, author_name, author_avatar, description, telemetry) VALUES
(1, 'Tomato Flowering Stage in Block A', 'Roma Tomatoes', 'Growth Progress', '/src/assets/roma_tomatoes.png', '2026-08-25', 'Ngozi Obi', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=60', 'First flowering nodes observed in row 3 to 10 of Field Block A. Soil moisture levels are hovering around 70%. Pollinator activity is excellent. No pests observed.', '{"stage": "Flowering", "moisture": "70%", "ph": "6.4", "temp": "28°C"}'),
(2, 'Habanero Peppers Color Turn', 'Habanero Pepper', 'Growth Progress', '/src/assets/habanero_pepper.png', '2026-08-24', 'Baba Tunde', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=60', 'Peppers are starting to ripen and change color from dark green to bright orange/red. Harvesting scheduled to begin next Monday.', '{"stage": "Ripening", "moisture": "65%", "ph": "6.2", "temp": "30°C"}'),
(3, 'Maize Height Performance Block C', 'African Corn', 'Growth Progress', '/src/assets/african_corn.png', '2026-08-22', 'Musa Haruna', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=60', 'Corn stands have reached average heights of 1.8m. Stalk width is excellent. Color is deep forest green, indicating adequate nitrogen availability.', '{"stage": "Vegetative (V8)", "moisture": "68%", "ph": "6.5", "temp": "29°C"}'),
(4, 'Cassava Harvest Selection Block B', 'Cassava Tubers', 'Harvesting', '/src/assets/cassava_tubers.png', '2026-08-19', 'Chioma Ade', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=60', 'First block harvest. Tuber sizing checked. Average weight per plant stands at 4.2kg, exceeding our 3.8kg baseline.', '{"stage": "Harvest Ready", "moisture": "58%", "ph": "5.9", "temp": "27°C"}'),
(5, 'Sweet Potato Grading after Harvest', 'Sweet Potatoes', 'Harvesting', '/src/assets/sweet_potatoes.png', '2026-08-18', 'Baba Tunde', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=60', 'Tubers dug from Field Block D have been spread in storage shed to dry. Grade A yield is estimated at 75%.', '{"stage": "Post-Harvest", "moisture": "50%", "ph": "6.0", "temp": "26°C"}'),
(6, 'Bell Peppers in shade greenhouse 2', 'Yellow Bell Pepper', 'Infrastructure', '/src/assets/yellow_bell_pepper.png', '2026-08-21', 'Ngozi Obi', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=60', 'Shade net settings adjusted. Greenhouse temperature drop of 3.5 degrees logged. Peppers sizing up uniformly.', '{"stage": "Fruiting", "moisture": "75%", "ph": "6.3", "temp": "25°C"}')
ON CONFLICT (id) DO UPDATE SET 
    title = EXCLUDED.title,
    crop = EXCLUDED.crop,
    category = EXCLUDED.category,
    img = EXCLUDED.img,
    date = EXCLUDED.date,
    author_name = EXCLUDED.author_name,
    author_avatar = EXCLUDED.author_avatar,
    description = EXCLUDED.description,
    telemetry = EXCLUDED.telemetry;

-- 7. Seed Initial Gallery Comments Data
INSERT INTO public.gallery_comments (id, log_id, author, avatar, text, time) VALUES
(1, 1, 'Baba Tunde', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=60', 'Flower density looks much better than last season.', '2 days ago'),
(2, 1, 'Chioma Ade', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=60', 'Keep moisture high this week to prevent early bud drop.', '1 day ago'),
(3, 2, 'Ngozi Obi', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=60', 'Ready to pick on Monday. I will prepare the crates.', '2 days ago'),
(4, 3, 'Chioma Ade', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=60', 'Fertigation cycle in Block C is showing great results.', '3 days ago'),
(5, 4, 'Baba Tunde', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=60', 'Tubers are large and firm. Excellent starch quality.', '1 week ago'),
(6, 5, 'Musa Haruna', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=60', 'No signs of wireworm or rot. Good work.', '1 week ago'),
(7, 6, 'Ngozi Obi', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=60', 'Ripening expected in about 12 days.', '5 days ago')
ON CONFLICT (id) DO UPDATE SET 
    log_id = EXCLUDED.log_id,
    author = EXCLUDED.author,
    avatar = EXCLUDED.avatar,
    text = EXCLUDED.text,
    time = EXCLUDED.time;

-- 8. Reset Auto-Increment Sequences
SELECT setval(pg_get_serial_sequence('public.products', 'id'), coalesce(max(id), 1) + 1) FROM public.products;
SELECT setval(pg_get_serial_sequence('public.gallery_logs', 'id'), coalesce(max(id), 1) + 1) FROM public.gallery_logs;
SELECT setval(pg_get_serial_sequence('public.gallery_comments', 'id'), coalesce(max(id), 1) + 1) FROM public.gallery_comments;

-- 9. Create Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
    id TEXT PRIMARY KEY,
    customer JSONB NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    time TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    items JSONB NOT NULL,
    delivery_fee INT NOT NULL DEFAULT 2000,
    payment_method TEXT NOT NULL DEFAULT 'Bank Transfer',
    payment_status TEXT NOT NULL DEFAULT 'Pending',
    notes TEXT,
    timeline JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security (RLS) for Orders
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Set up RLS Policies for Orders
DROP POLICY IF EXISTS "Allow anonymous read access" ON public.orders;
CREATE POLICY "Allow anonymous read access" ON public.orders FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow anonymous write access" ON public.orders;
CREATE POLICY "Allow anonymous write access" ON public.orders FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anonymous update access" ON public.orders;
CREATE POLICY "Allow anonymous update access" ON public.orders FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow anonymous delete access" ON public.orders;
CREATE POLICY "Allow anonymous delete access" ON public.orders FOR DELETE USING (true);

