-- 1. Create Gallery Logs Table
CREATE TABLE IF NOT EXISTS public.gallery_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    crop TEXT NOT NULL,
    category TEXT NOT NULL,
    img TEXT NOT NULL, -- Base64 Data URL or storage bucket URL
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    author_name TEXT NOT NULL,
    author_avatar TEXT NOT NULL,
    description TEXT,
    telemetry JSONB NOT NULL DEFAULT '{"stage": "N/A", "moisture": "N/A", "ph": "N/A", "temp": "N/A"}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create Comments Table
CREATE TABLE IF NOT EXISTS public.gallery_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_id BIGINT REFERENCES public.gallery_logs(id) ON DELETE CASCADE NOT NULL,
    author TEXT NOT NULL DEFAULT 'Administrator',
    avatar TEXT NOT NULL,
    text TEXT NOT NULL,
    time TEXT NOT NULL DEFAULT 'Just now',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Create Settings Table (Single-row configuration)
CREATE TABLE IF NOT EXISTS public.system_settings (
    id INT PRIMARY KEY DEFAULT 1,
    profile_name TEXT NOT NULL DEFAULT '',
    profile_email TEXT NOT NULL DEFAULT '',
    profile_phone TEXT DEFAULT '',
    profile_role TEXT NOT NULL DEFAULT '',
    profile_location TEXT DEFAULT '',
    profile_avatar TEXT NOT NULL DEFAULT '',
    low_stock_alert BOOLEAN NOT NULL DEFAULT TRUE,
    order_success_alert BOOLEAN NOT NULL DEFAULT FALSE,
    weekly_report BOOLEAN NOT NULL DEFAULT TRUE,
    two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT check_single_row CHECK (id = 1)
);

-- Enable Row Level Security (RLS) or public access bypass for testing
ALTER TABLE public.gallery_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;

-- Set up RLS Policies (allows reads, inserts, and deletes for all users)
DROP POLICY IF EXISTS "Allow anonymous read access" ON public.gallery_logs;
CREATE POLICY "Allow anonymous read access" ON public.gallery_logs FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow anonymous write access" ON public.gallery_logs;
CREATE POLICY "Allow anonymous write access" ON public.gallery_logs FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anonymous delete access" ON public.gallery_logs;
CREATE POLICY "Allow anonymous delete access" ON public.gallery_logs FOR DELETE USING (true);

DROP POLICY IF EXISTS "Allow anonymous read access" ON public.gallery_comments;
CREATE POLICY "Allow anonymous read access" ON public.gallery_comments FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow anonymous write access" ON public.gallery_comments;
CREATE POLICY "Allow anonymous write access" ON public.gallery_comments FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anonymous read access" ON public.system_settings;
CREATE POLICY "Allow anonymous read access" ON public.system_settings FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow anonymous update access" ON public.system_settings;
CREATE POLICY "Allow anonymous update access" ON public.system_settings FOR UPDATE USING (true);

-- Insert Default Settings Single Row
INSERT INTO public.system_settings (id) VALUES (1) ON CONFLICT DO NOTHING;

-- 4. Create Products Table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    unit TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'published',
    img TEXT NOT NULL, -- Base64 Data URL or storage bucket URL
    qty INT NOT NULL DEFAULT 0,
    min INT NOT NULL DEFAULT 50,
    max INT NOT NULL DEFAULT 500,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Set up RLS Policies for Products
DROP POLICY IF EXISTS "Allow anonymous read access" ON public.products;
CREATE POLICY "Allow anonymous read access" ON public.products FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow anonymous write access" ON public.products;
CREATE POLICY "Allow anonymous write access" ON public.products FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anonymous update access" ON public.products;
CREATE POLICY "Allow anonymous update access" ON public.products FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow anonymous delete access" ON public.products;
CREATE POLICY "Allow anonymous delete access" ON public.products FOR DELETE USING (true);
-- 8. Reset Auto-Increment Sequences
SELECT setval(pg_get_serial_sequence('public.products', 'id'), 1, false);
SELECT setval(pg_get_serial_sequence('public.gallery_logs', 'id'), 1, false);
SELECT setval(pg_get_serial_sequence('public.gallery_comments', 'id'), 1, false);

-- 9. Create Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
    id TEXT PRIMARY KEY,
    customer JSONB NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    time TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    items JSONB NOT NULL,
    delivery_fee INT NOT NULL DEFAULT 2000,
    notes TEXT,
    timeline JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security (RLS) for Orders
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Set up RLS Policies for Orders
DROP POLICY IF EXISTS "Allow anonymous read access" ON public.orders;
CREATE POLICY "Allow anonymous read access" ON public.orders FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow anonymous write access" ON public.orders;
CREATE POLICY "Allow anonymous write access" ON public.orders FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anonymous update access" ON public.orders;
CREATE POLICY "Allow anonymous update access" ON public.orders FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow anonymous delete access" ON public.orders;
CREATE POLICY "Allow anonymous delete access" ON public.orders FOR DELETE USING (true);

