-- 1. Create Gallery Logs Table
CREATE TABLE IF NOT EXISTS public.gallery_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    crop TEXT NOT NULL,
    category TEXT NOT NULL,
    img TEXT NOT NULL, -- Base64 Data URL or storage bucket URL
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    author_name TEXT NOT NULL,
    author_avatar TEXT NOT NULL,
    description TEXT,
    telemetry JSONB NOT NULL DEFAULT '{"stage": "N/A", "moisture": "N/A", "ph": "N/A", "temp": "N/A"}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create Comments Table
CREATE TABLE IF NOT EXISTS public.gallery_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_id BIGINT REFERENCES public.gallery_logs(id) ON DELETE CASCADE NOT NULL,
    author TEXT NOT NULL DEFAULT 'Administrator',
    avatar TEXT NOT NULL,
    text TEXT NOT NULL,
    time TEXT NOT NULL DEFAULT 'Just now',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Create Settings Table (Single-row configuration)
CREATE TABLE IF NOT EXISTS public.system_settings (
    id INT PRIMARY KEY DEFAULT 1,
    profile_name TEXT NOT NULL DEFAULT 'Senior Director Baba Tunde',
    profile_email TEXT NOT NULL DEFAULT 'baba.tunde@resolvefarms.com',
    profile_phone TEXT DEFAULT '+234 803 123 4567',
    profile_role TEXT NOT NULL DEFAULT 'Senior Farm Director',
    profile_location TEXT DEFAULT 'Enugu Field Block A-C',
    profile_avatar TEXT NOT NULL DEFAULT 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=60',
    temp_unit TEXT NOT NULL DEFAULT '°C',
    area_unit TEXT NOT NULL DEFAULT 'Hectares',
    moisture_min INT NOT NULL DEFAULT 60,
    ph_min NUMERIC(3,1) NOT NULL DEFAULT 6.0,
    ph_max NUMERIC(3,1) NOT NULL DEFAULT 7.2,
    temp_warning_max INT NOT NULL DEFAULT 35,
    low_stock_alert BOOLEAN NOT NULL DEFAULT TRUE,
    order_success_alert BOOLEAN NOT NULL DEFAULT FALSE,
    weekly_report BOOLEAN NOT NULL DEFAULT TRUE,
    two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT check_single_row CHECK (id = 1)
);

-- Enable Row Level Security (RLS) or public access bypass for testing
ALTER TABLE public.gallery_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;

-- Set up RLS Policies (allows reads, inserts, and deletes for all users)
DROP POLICY IF EXISTS "Allow anonymous read access" ON public.gallery_logs;
CREATE POLICY "Allow anonymous read access" ON public.gallery_logs FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow anonymous write access" ON public.gallery_logs;
CREATE POLICY "Allow anonymous write access" ON public.gallery_logs FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anonymous delete access" ON public.gallery_logs;
CREATE POLICY "Allow anonymous delete access" ON public.gallery_logs FOR DELETE USING (true);

DROP POLICY IF EXISTS "Allow anonymous read access" ON public.gallery_comments;
CREATE POLICY "Allow anonymous read access" ON public.gallery_comments FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow anonymous write access" ON public.gallery_comments;
CREATE POLICY "Allow anonymous write access" ON public.gallery_comments FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anonymous read access" ON public.system_settings;
CREATE POLICY "Allow anonymous read access" ON public.system_settings FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow anonymous update access" ON public.system_settings;
CREATE POLICY "Allow anonymous update access" ON public.system_settings FOR UPDATE USING (true);

-- Insert Default Settings Single Row
INSERT INTO public.system_settings (id) VALUES (1) ON CONFLICT DO NOTHING;
